### ISSUE TITLE
 Shortcut for "Mizar Compile"?

### ISSUE THREAD

**Issue by CoghettoR** [mimosa-project/emvscode#67]
Is there a shortcut for "Mizar Compile"?
Thanks

**Comment by aabaa** [comment]
Shortcut keys are not provided yet; please use VSCode's key binding function to add them.
[Key Bindings for Visual Studio Code](https://code.visualstudio.com/docs/getstarted/keybindings)

**Comment by CoghettoR** [comment]
Thank you. I am very happy with your suggestion.
